#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void LoadButtonOnButtonClick( wxCommandEvent& event );
		void RotateButton1OnButtonClick( wxCommandEvent& event );
		void RotateButton2OnButtonClick( wxCommandEvent& event );
		void ShearButtonOnButtonClick( wxCommandEvent& event );
		void DistortionButtonOnButtonClick( wxCommandEvent& event );
		void SaveButtonOnButtonClick( wxCommandEvent& event );
		void ImgScrolledWindowOnUpdateUI( wxUpdateUIEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

	protected:
		wxImage Img_Org;
		wxImage* Img_Cpy;
		void Draw();
		void RotateImagePlane(double angle, int x, int y);



		//punkt 3: Pochylenie obrazu (Shear)
		void ShearX(double angle); //przechylenie na osi x
		void ShearY(double angle); //przechylenie na osi y
		wxImage* CutXborder(wxImage* Img); //Funkcja usuwa pusty obszar na lewo i prawo od obrazka który mo¿e powstaæ gdy wywo³a siê ShearX
		wxImage* CutYborder(wxImage* Img); //Funkcja usuwa pusty obszar na górze i dole od obrazka który mo¿e powstaæ gdy wywo³a siê ShearY
		//










};

#endif // __GUIMyFrame1__
