#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void LoadButtonOnButtonClick( wxCommandEvent& event );
		void RotateButton1OnButtonClick( wxCommandEvent& event );
		void RotateButton2OnButtonClick( wxCommandEvent& event );
		void ShearButtonOnButtonClick( wxCommandEvent& event );
		void DistortionButtonOnButtonClick( wxCommandEvent& event );
		void SaveButtonOnButtonClick( wxCommandEvent& event );
		void ImgScrolledWindowOnUpdateUI( wxUpdateUIEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

	protected:
		wxImage Img_Org;
		wxImage* Img_Cpy;
		void Draw();
		void RotateImagePlane(double angle, int x, int y);














};

#endif // __GUIMyFrame1__
