#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include "vecmat.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void LoadButtonOnButtonClick( wxCommandEvent& event );
		void RotateButton1OnButtonClick( wxCommandEvent& event );
		void RotateButton2OnButtonClick( wxCommandEvent& event );
		void ShearButtonOnButtonClick( wxCommandEvent& event );
		void DistortionButtonOnButtonClick( wxCommandEvent& event );
		void SaveButtonOnButtonClick( wxCommandEvent& event );
		void ImgScrolledWindowOnUpdateUI( wxUpdateUIEvent& event );
		void OnCheckBoxToggle(wxCommandEvent& event);
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

	protected:
		wxImage Img_Org;
		wxImage* Img_Cpy;
		void Draw();
		void RotateImagePlane(double angle, int x, int y);

		//Punkt2 i punkt1
		Vector4* vectors = nullptr;
		int width;
		int height;
		int size;
		wxSlider* slider1;
		wxSlider* slider2;
		void _Rotation(wxCommandEvent& e);
		void RotateOtherAxis(double angle1, double angle2);
		wxImage BilinearInterpolate(const wxImage& srcImage, int newWidth, int newHeight);


		//punkt 3: Pochylenie obrazu (Shear)
		void ShearX(double angle); //przechylenie na osi x
		void ShearY(double angle); //przechylenie na osi y
		wxImage* CutXborder(wxImage* Img); //Funkcja usuwa pusty obszar na lewo i prawo od obrazka który mo¿e powstaæ gdy wywo³a siê ShearX
		wxImage* CutYborder(wxImage* Img); //Funkcja usuwa pusty obszar na górze i dole od obrazka który mo¿e powstaæ gdy wywo³a siê ShearY
		//


		//punkt 4 checkbox 
		int* flag_handler; //potrzebne mi do zmieniania stanu txtctr
		wxTextCtrl* text_handler; //potrzebne mi do zmieniania stanu txtctr
		wxCheckBox* checkBox_handler; //potrzebne mi do zmieniania stanu txtctr
		void CorrectDisortion(double A, double B, double C, double D, int flag);








};

#endif // __GUIMyFrame1__
