#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include "vecmat.h"
#include <vector>
//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void LoadButtonOnButtonClick( wxCommandEvent& event );
		void RotateButton1OnButtonClick( wxCommandEvent& event );
		void RotateButton2OnButtonClick( wxCommandEvent& event );
		void ShearButtonOnButtonClick( wxCommandEvent& event );
		void DistortionButtonOnButtonClick( wxCommandEvent& event );
		void SaveButtonOnButtonClick( wxCommandEvent& event );
		void ImgScrolledWindowOnUpdateUI( wxUpdateUIEvent& event );
		void OnCheckBoxToggle(wxCommandEvent& event);
		void GridBoxToggle(wxCommandEvent& event);
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		~GUIMyFrame1();

	protected:
		wxImage Img_Org;
		wxImage* Img_Cpy;
		void Draw();
		void RotateImagePlane(double angle, int x, int y);

		//Punkt2
		Vector4* vectors = nullptr;
		int width;
		int height;
		int size;
		wxSlider* slider1;
		wxSlider* slider2;
		wxSlider* slider3;
		wxSlider* slider4;
		wxSlider* slider5;
		int old_zmiana1 = 0;
		int old_zmiana2 = 0;
		void _Rotation(wxCommandEvent& e);
		void RotateOtherAxis(int angle1, int angle2, int zmiana1, int zmiana2, int camera_pos );


		//punkt 3: Pochylenie obrazu (Shear)
		void ShearX(double angle); //przechylenie na osi x
		void ShearY(double angle); //przechylenie na osi y
		wxImage* CutXborder(wxImage* Img); //Funkcja usuwa pusty obszar na lewo i prawo od obrazka
		int FindCutLeft(wxImage* Img); //Funkcja znajduje szerokosc pustego obszaru na lewo od obrazka
		int FindCutRight(wxImage* Img); //Funkcja znajduje szerokosc pustego obszaru na prawo od obrazka
		wxImage* CutYborder(wxImage* Img); //Funkcja usuwa pusty obszar na górze i dole od obrazka
		int FindCutTop(wxImage* Img); //Funkcja znajduje wysokosc pustego obszaru nad obrazkiem
		int FindCutBottom(wxImage* Img); //Funkcja znajduje wysokosc pustego obszaru pod obrazkiem
		//


		//punkt 4 checkbox 
		int* flag_handler; //potrzebne mi do zmieniania stanu txtctr
		wxTextCtrl* text_handler; //potrzebne mi do zmieniania stanu txtctr
		wxCheckBox* checkBox_handler; //potrzebne mi do zmieniania stanu txtctr
		void CorrectDisortion(double A, double B, double C, double D, int flag);


		//siateczka esz
		void ShowGrid();
		void HideGrid();


		std::vector<wxImage*> ImagesHistory;
		wxMenuBar* menuBar;
		wxMenu* edit;

		enum {
			ID_MENU_UNDO = 1000
		};





};

#endif // __GUIMyFrame1__
